name: Weekly AI Papers

on:
  schedule:
    # Run every Friday at 6 PM UTC (adjust timezone as needed)
    - cron: '0 18 * * 5'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  fetch-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run AI Papers Agent
      env:
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        SUBSTACK_EMAIL: ${{ secrets.SUBSTACK_EMAIL }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python main.py
    
    - name: Commit database updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add published_papers.db
        git diff --staged --quiet || git commit -m "Update published papers database - $(date +'%Y-%m-%d')"
        git push || echo "No changes to push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
